### ISSUE TITLE
Multitargeting .NET Framework and .NET Core

### ISSUE THREAD

**Issue by gerardog** [SimonCropp/NetCoreConsole#1]
What if I want to build to both .Net Fw and .Net Core?
Changing:

    <TargetFramework>netcoreapp2.1</TargetFramework>

with 

    <TargetFrameworks>netcoreapp2.1;net472</TargetFrameworks>

Throws a variety of errors during build. Could you please address those? 
Thank you!

**Comment by SimonCropp** [comment]
sorry i dont have the capacity to work on this in my spare time for free. happy to accept a PR if you solve it. otherwise I am happy to quote you an hourly rate.
